// Windissect exhaustive candidate class surface for Windows.Management.Workplace.dll.
// Experimental: declarations may contain unresolved PDB language ambiguities.
#pragma once

#include "windissect_abi.h"
#include "windissect_forwards.h"
#include "windissect_vcalls.h"
#include "windissect_calls.h"
#include "utilities/NamedPolicyStatics.h"
#include "utilities/MdmAllowPolicyStatics.h"
#include "utilities/MdmAlert.h"
#include "utilities/NamedPolicyData.h"
#include "utilities/MdmSession.h"
#include "utilities/MdmSessionManagerStatics.h"
#include "utilities/Details.h"
#include "utilities/FtmBase.h"
#include "accessibility/MdmSyncTraceProvider.h"
#include "utilities/EventTargetArray.h"
#include "utilities/ModuleBase.h"
#include "utilities/HStringReference.h"
#include "utilities/WeakReferenceImpl.h"
#include "utilities/HString.h"
#include "utilities/ComTaskPoolHandler.h"
#include "utilities/AgileRef.h"
#include "utilities/WeakRef.h"
#include "utilities/SRWLock.h"
#include "utilities/detail.h"
#include "utilities/RpcOptionsHelper.h"
#include "utilities/SyncLockExclusive.h"
#include "utilities/SyncLockShared.h"
#include "utilities/Foundation.h"
#include "utilities/MdmSyncBucket.h"
#include "utilities/Streams.h"
#include "utilities/DefaultMarshaler.h"
